### ISSUE TITLE
java.lang.IllegalArgumentException: Proper ID is not defined for field, again

### ISSUE THREAD

**Issue by Narayane** [jakenjarvis/Android-OrmLiteContentProvider#20]
Hi,

I have the same error than the other "invalid" issue but not in the same context.
I followed your README.md with the contract automatic generation way.
I design an app targeting API 19 with API 9 for min, using ormlite 4.48.
Contract is successfully generated but when I launch my app, I have this error : 

FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.sebastien.balard.android.squareup.domain.provider.SQProvider: java.lang.IllegalArgumentException: Proper ID is not defined for field.

 Caused by: java.lang.IllegalArgumentException: Proper ID is not defined for field.
            at com.tojc.ormlite.android.framework.TableInfo.<init>(TableInfo.java:120)
            at com.tojc.ormlite.android.framework.MatcherController.addTableClass(MatcherController.java:212)
            at com.tojc.ormlite.android.framework.MatcherController.add(MatcherController.java:87)
            at com.sebastien.balard.android.squareup.domain.provider.SQProvider.onCreate(SQProvider.java:22)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:815)
            at android.app.ActivityThread.installProvider(ActivityThread.java:4244)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:3954)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3910)
            at android.app.ActivityThread.access$2200(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1098)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:150)
            at android.app.ActivityThread.main(ActivityThread.java:4385)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
            at dalvik.system.NativeStart.main(Native Method)

---

Domain class

@Contract
@DatabaseTable(tableName = "square_up_event", daoClass = EventDaoImpl.class)
@DefaultContentUri(authority = "com.sebastien.balard.android.squareup.domain", path = "square_up_event")
@DefaultContentMimeTypeVnd(name = "com.sebastien.balard.android.squareup.domain.provider", type = "square_up_event")
public class Event implements Serializable {

```
private static final long serialVersionUID = 3904383442695594954L;

@DatabaseField(generatedId = true, columnName = "event_id", canBeNull = false)
@DefaultSortOrder
protected Long id;
```

Content Provider

public class SQProvider extends OrmLiteSimpleContentProvider<DbHelper> {

```
@Override
protected Class<DbHelper> getHelperClass() {
    return DbHelper.class;
}

@Override
public boolean onCreate() {
    setMatcherController(new MatcherController()
            .add(Event.class, MimeTypeVnd.SubType.DIRECTORY, "", EventContract.CONTENT_URI_PATTERN_MANY)
            .add(Event.class, MimeTypeVnd.SubType.ITEM, "#", EventContract.CONTENT_URI_PATTERN_ONE));
    return true;
}
```

} 

Content provider element in my AndroidManifest.xml

< provider android:name="com.sebastien.balard.android.squareup.domain.provider.SQProvider" android:authorities="com.sebastien.balard.android.squareup.domain" android:exported="false" />

Can you help me ?
Thanks.

**Comment by jakenjarvis** [comment]
Hello, @Narayane 
You must be reviewed the table layout.

```
@DatabaseField(generatedId = true, columnName = "event_id", canBeNull = false)
@DefaultSortOrder
protected Long id;
```

Please correct this as follows.

```
@DatabaseField(columnName = BaseColumns._ID, generatedId = true)
@DefaultSortOrder
protected Long id;
```

Please refer to the following URL for more information. See [Data design considerations].
https://developer.android.com/guide/topics/providers/content-provider-creating.html#ContentURI

Your issue will be solved by this probably ;)

**Comment by Narayane** [comment]
Hi @jakenjarvis ,

Ok for your suggestion but if BaseColumns._ID does not match my real column name in db, is it complete ?

I have an existing app and my column names do not match my class attributes names (However I could do this by updating my db schema if there is no other alternative).
For me, "in a perfect world" (I use automatic contract generation) BaseColumn.\* values should be equal to relative "field.getAnnotation(DatabaseField.class).columnName()" if exists instead of using "fieldName" at line 312 of com.tojc.ormlite.android.compiler.ContractAnnotationProcessor to solve my problem. But, maybe I am wrong on this point, tell me ?

Here BaseColumns list in my generated contract : 

public static final String ID = "id"; // event_id in db
public static final String NAME = "name"; // event_name in db
public static final String STARTDATE = "startDate"; // event_start_date in db
public static final String ENDDATE = "endDate"; // event_end_date in db
public static final String CURRENCY = "currency"; // event_currency in db

I tried to import your project in Android Studio to test this by myself but I have a problem that I can't not resolve for the moment during ormlite-content-provider-library project configuration : 

groovy.lang.MissingPropertyException: Could not find property 'allJava' on source set main.

Regards.

**Comment by jakenjarvis** [comment]
Hi @Narayane
My English was weird? You must modify the table layout.
I can't explain to you, because I'm not good at English. X(
Please check by searching on your own.

Please also see the following sites:
http://stackoverflow.com/questions/3192064/about-id-field-in-android-sqlite
http://stackoverflow.com/questions/3359414/android-column-id-does-not-exist
