### ISSUE TITLE
Class is not annotated with the @Contract annotation.

### ISSUE THREAD

**Issue by ghost** [jakenjarvis/Android-OrmLiteContentProvider#21]
When I compile with this `compile 'com.tojc.ormlite.android:ormlite-content-provider-library:1.0.4'` and removing the old jar (`v1.0.3`) this exception is throw :

```
    main java.lang.Exception: Class class com.android.example.model.accounts is not annotated with the @Contract annotation.
            at com.octo.android.robospice.persistence.ormlite.RoboSpiceContentProvider.onCreate(RoboSpiceContentProvider.java:64)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:1686)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:1655)
            at android.app.ActivityThread.installProvider(ActivityThread.java:4964)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4559)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4499)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)


    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalArgumentException: unknown uri : content://com.android.example.model/accounts
            at com.tojc.ormlite.android.OrmLiteDefaultContentProvider.query(OrmLiteDefaultContentProvider.java:162)
            at android.content.ContentProvider.query(ContentProvider.java:950)
            at android.content.ContentProvider$Transport.query(ContentProvider.java:210)
            at android.content.ContentResolver.query(ContentResolver.java:478)
            at android.content.ContentResolver.query(ContentResolver.java:422)
            at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:49)
            at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:35)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

The exception is throw [here](https://github.com/stephanenicolas/robospice/blob/b3ede624b4ec2191d8eef10dede089fc091bcc95/extensions/robospice-ormlite-content-provider-parent/robospice-ormlite-content-provider/src/main/java/com/octo/android/robospice/persistence/ormlite/RoboSpiceContentProvider.java#L30). With the old library (`v1.0.3`) there's not such error created.

How can I make `v1.0.4` work with `robospice-ormlite-content-provider`?

**Comment by jakenjarvis** [comment]
Hi @GerritHoekstra 
Hmm, Since I do not use RoboSpice, I do not know much about it.

Contract annotation, has been changed from RUNTIME to SOURCE. This may have an effect.
https://github.com/jakenjarvis/Android-OrmLiteContentProvider/compare/06462df4988ffe3bffd00afb1f3831e2e720c051...6def374d41fd4240f3cbc61bf140f3a93df417dc#diff-50

```
- @Retention(RetentionPolicy.RUNTIME)
+ @Retention(RetentionPolicy.SOURCE)
@Target({ ElementType.TYPE })
public @interface Contract {
```
